name: datarun
description: Datarun, runs and manages you activities data workflows.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.0.1+5

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  material_design_icons_flutter: ^5.0.6996
  d2_remote:
    path: ./data-run-sdk
  equatable: ^2.0.5
  intl: ^0.19.0
  shared_preferences: ^2.0.15
  reflectable: ^4.0.5
  percent_indicator: ^4.2.3
  reactive_forms: ^17.0.1
  uuid: ^4.5.0
  fast_immutable_collections: ^10.2.4
#  expressions: ^0.2.3
  expressions: ^0.2.5+2
  flutter_sticky_header: ^0.7.0
  collection: ^1.18.0
  reactive_dropdown_search: ^5.0.5
  sliver_tools: ^0.2.12
  flutter_fancy_tree_view: ^1.6.0
  gs1_barcode_parser: ^1.1.0
  device_info_plus: ^11.1.1
  connectivity_plus: ^6.1.0
  mobile_scanner: ^6.0.2
#  image_picker: ^1.1.2
  sentry_flutter: ^8.10.1
#  dropdown_search: ^6.0.1
#  fl_chart: ^0.69.2
  flutter_riverpod: 3.0.0-dev.3
  hooks_riverpod: 3.0.0-dev.3
  freezed_annotation: ^2.4.1
  riverpod_annotation: 3.0.0-dev.3
#  flutter_map: ^4.0.0
#  latlong2: ^0.8.2
  package_info_plus: ^8.1.2
  http: ^0.13.4
  timeago: ^3.7.0
#  flutter_barcode_scanner: ^2.0.0

## for Expression need to override petitparser
#  expression_language: ^1.0.1
#dependency_overrides:
#  petitparser: ^6.0.2
dev_dependencies:
  test: ^1.21.0
  freezed: ^2.5.2
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  http_mock_adapter: ^0.4.4
  reactive_forms_generator:
  riverpod_generator: 3.0.0-dev.11
  riverpod_lint: 3.0.0-dev.4
  custom_lint: ^0.5.11
  flutter_launcher_icons: ^0.13.1

#flutter_launcher_icons:
#  android: "launcher_icon"
#  adaptive_icon_background: "assets/launcher_icon/ic_launcher.png"
#  image_path: "assets/launcher_icon/ic_launcher.png"
#  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/l10n/
    - assets/launcher_icon/
#    - assets/images/
# analyzer:
#   strong-mode: true
#   language:
#     enableSuperMixins: true
flutter_intl:
  enabled: true
